### ISSUE TITLE
update pypi please

### ISSUE THREAD

**Issue by drandreaskrueger** [ConsenSys/ethjsonrpc#14]
pip install ethjsonrpc

and then 

    cat ...site-packages/ethjsonrpc/client.py | grep call_with_transaction

shows

    def call_with_transaction(self, from_, address, sig, args, gas=None, gas_price=None):

while the [newest code](https://github.com/ConsenSys/ethjsonrpc/blob/682ee21e281fd6ac780b147d2981b255e2f7cd6f/ethjsonrpc/client.py#L110) has the needed `value` parameter

    def call_with_transaction(self, from_, address, sig, args, gas=None, gas_price=None, value=None):

--> https://pypi.python.org/pypi/ethjsonrpc

Thanks.

**Comment by drandreaskrueger** [comment]
Of course, my personal installation I could easily patch, by manually copying a file. But for the end users that I am writing my manuals for - that'd be an unnecessary hassle.

Thanks.

**Comment by maurycyp** [comment]
@drandreaskrueger Hi, thanks for the reminder.  I'll try to push out a new version today.

**Comment by maurycyp** [comment]
@drandreaskrueger OK, I uploaded a new version 0.2.9 to PyPI.  Please let me know if you have any other issues.

Closing.

**Comment by drandreaskrueger** [comment]
Thanks a lot. And thanks you for your great library, by the way. Very useful.
