### ISSUE TITLE
Does not work with Geth 1.6.6

### ISSUE THREAD

**Issue by emunsing** [ConsenSys/ethjsonrpc#36]
Changes in the RPC implementation in Geth appear to have broken the demo- specifically, the calls to c.call() and  c.call_with_transaction()  return a 

`BadResponseError: {u'jsonrpc': u'2.0', u'id': 1, u'error': {u'message': u'invalid argument 0: missing 0x prefix for hex data', u'code': -32602}}`

Geth v1.6.6, ethjsonrpc v0.3.0, python 2.7.12, Mac OS 10.11.6 (El Capitan). 

The same demo worked for me in December, but I believe that changes to the RPC hooks in geth have affected this.

**Comment by emunsing** [comment]
It looks like pull request #27 might work for addressing this; could this (or a variation) please be accepted?

**Comment by revandarth** [comment]
I am seeing the same issue, did you resolve this issue? Any help would be greatly appreciated.

`c.call_with_transaction(c.eth_coinbase(), *******, 'set_s(string)', ['Hello, world'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ethjsonrpc/client.py", line 130, in call_with_transaction
    gas_price=gas_price, value=value)
  File "/usr/local/lib/python2.7/dist-packages/ethjsonrpc/client.py", line 343, in eth_sendTransaction
    return self._call('eth_sendTransaction', [params])
  File "/usr/local/lib/python2.7/dist-packages/ethjsonrpc/client.py", line 65, in _call
    raise BadResponseError(response)
ethjsonrpc.exceptions.BadResponseError: {u'jsonrpc': u'2.0', u'id': 1, u'error': {u'message': u'invalid argument 0: missing 0x prefix for hex data', u'code': -32602}}`

**Comment by fjblau** [comment]
I am also still seeing this error and can't seem to find a resolution.
