### ISSUE TITLE
Connecting with Infura support ?

### ISSUE THREAD

**Issue by kaviyarasu7** [ConsenSys/ethjsonrpc#40]
Dose this library supports Infura ?
Just tried a below script to connect with Infura.
`>>> c = EthJsonRpc('https://rinkeby.infura.io/3wNHisYyMhD4B0UTAoWs')
>>> c.net_version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ethjsonrpc/client.py", line 159, in net_version
    return self._call('net_version')
  File "ethjsonrpc/client.py", line 55, in _call
    raise ConnectionError
ethjsonrpc.exceptions.ConnectionError
`
Kindly help.

**Comment by reiven** [comment]
Dont think so, i've tried to remove the protocol and changed the port, but probably the client needed some changes to work
