### ISSUE TITLE
Remove trailing 'L' off the string returns from `hex` [Python 2.x]

### ISSUE THREAD

**Issue by weipin** [ConsenSys/ethjsonrpc#7]
Hi,

Seems `hex` is being used to convert integer to hex string, when ethjsonrpc constructs the RPC requests (the argument `value` of `eth_sendTransaction` specifically). 

The `hex` in Python 2.x will represent a `long` with a trailing 'L':

```
>>> hex(1L)
'0x1L'

>>> hex(12345678901234567890)
'0xab54a98ceb1f0ad2L'
```

'L' isn't legal for a hex string. The odd fact is that geth RPC often accepts such false format without complaining, but not always. Here is an error message from "Geth/v1.4.0-unstable/linux/go1.5.1":

```
{"code":-32602,"message":"Unable to parse number"}
```

Removing the tailing 'L' solved the error.

While still no idea what causes the difference (the error only happens on one of the geth instances we installed), the error is real. Worth mentioning the issue here in case others are having the same problem.

It also worth a simple fix like `hex(x).rstrip("L")` since the hex string feeds geth PRC could indeed contain the illegal character.

**Comment by maurycyp** [comment]
Thank you, fixed in https://github.com/ConsenSys/ethjsonrpc/commit/fe27f551aa943532e0a12740fb02ab998345dac5 .

**Comment by DevFares** [comment]
Thank you 👍
